- name: Clone the dotfiles repo
  git: repo="git@github.com:aarbatova/dotfiles.git" dest=/home/{{ user }}/.dotfiles
  sudo: false

- name: Symlink dotfiles
  command: /home/{{ user }}/.dotfiles/install.sh
  sudo: false

