- name: Install ruby
  yum: name=ruby state=present

- name: install homesick
  gem: name=homesick state=present
  sudo: false

- name: Clone the homesick repos
  command: /home/{{ user }}/bin/homesick clone {{ item.repo }} creates=/home/{{ user }}/.homesick/repos/{{ item.name }}
  with_items:
  - { repo: "git@github.com:vaskas/dotfiles.git",   name: dotfiles   }
  - { repo: "git@github.com:vaskas/zsh-themes.git", name: zsh-themes }
  - { repo: "git@github.com:vaskas/tmuxfiles.git",  name: tmuxfiles  }
  - { repo: "git@github.com:vaskas/vimfiles.git",   name: vimfiles   }
  sudo: false

- name: Symlink dotfiles
  command: /home/{{ user }}/bin/homesick symlink --force dotfiles
  sudo: false

- name: Symlink other repos
  command: /home/{{ user }}/bin/homesick symlink {{ item }}
  with_items: [ 'zsh-themes', 'tmuxfiles', 'vimfiles']
  sudo: false

- name: Install vim plugins
  command: /home/{{ user }}/.vim/derps bundle.dep chdir=/home/{{ user }}/.vim
  sudo: false
