- name: Install software
  yum: pkg={{ item }} state=present
  with_items:
    - vim
    - tmux
    - htop
    - ncdu
    - ranger
    - unrar
    - parallel
    - zsh
    - git

- include: dotfiles.yml

