- name: Install RPMFusion repositories
  yum: name={{ item }} state=present
  with_items:
    - http://download1.rpmfusion.org/free/fedora/rpmfusion-free-release-20.noarch.rpm
    - http://download1.rpmfusion.org/nonfree/fedora/rpmfusion-nonfree-release-20.noarch.rpm

