- name: Install software
  yum: pkg={{ item }} state=present
  with_items:
    - firefox
    - qutim
    - quassel
    - wireshark
    - wireshark-gnome
    - nmap
    - tcpdump
    - youtube-dl
    - wget
    - aria2

- name: Add user to the wireshark group
  user: name={{ user }} groups="wireshark" append=yes

- include: tor.yml
- include: owncloud.yml

