- include: infinality.yml

- name: Install software
  yum: pkg={{ item }} state=installed
  with_items:
    - libreoffice
    - dia

- name: Remove calligra suite
  yum: pkg=calligra-{{ item }} state=absent
  with_items:
   - kdchart
   - words
   - stage
   - sheets
   - libs
   - stage
   - core
   - words
   - sheets

- include: skype.yml

