- name: Install desktop software
  action: yum pkg={{ item }} state=installed
  with_items:
    - xcalib
    - firefox
    - gitg
    - qutim
    - quassel
    - clementine
    - digikam
    - libreoffice
    - gimp
    - kate
    - audacity
    - vlc
    - smplayer
    - wireshark
    - wireshark-gnome
  tags: gui-tools

- name: Add user to the wireshark group
  user: name={{ user }} groups="wireshark" append=yes

- name: Remove calligra suite
  yum: pkg=calligra-{{ item }} state=absent
  with_items: [ kdchart, words, stage, sheets, libs, core ]

- include: infinality.yml
- include: owncloud.yml
- include: tor.yml tags=tor
- include: non-free.yml

