- name: Install software
  yum: pkg={{ item }} state=installed
  with_items:
    - clementine
    - gimp
    - inkscape
    - ImageMagick
    - vlc

- name: Install codecs
  yum: pkg={{ item }} state=present
  with_items:
    - gstreamer-plugins-ugly
    - gstreamer-plugins-bad
    - gstreamer-ffmpeg

