- name: Install Google Chrome yum repo
  copy: src=google-chrome.repo dest=/etc/yum.repos.d/google-chrome.repo

- name: Install Google Chrome
  yum: pkg=google-chrome-stable state=present

- name: Apply the global fonts configuration
  copy: src=local.conf dest=/etc/fonts/local.conf

